data:
  input_file: "Stock Price.csv"
  model_file: "Stock_Price_Prediction_21_10.pkl"

preprocessing:
  time_span: [1, 3, 7, 14]
  feature_cols:
    - Stock_encoded
    - rolling_mean_1
    - rolling_mean_3
    - rolling_mean_7
    - rolling_mean_14
    - rolling_std_3
    - rolling_std_7
    - rolling_std_14
    - price_change_lag1
    - price_change_lag3
    - price_change_lag7
    - Price_Trend

  validation:
    required_columns:
      - Stock_Name
      - Close
      - Date
    max_missing_threshold: 0.1

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/stock_price_predictor.log"